# Generated by Django 3.0 on 2021-08-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default=' The Notary Mama ', max_length=255),
        ),
    ]
